name: Publish

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache RubyGems
      uses: actions/cache@v4
      env:
        cache-name: rubygems
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ruby ruby-dev ruby-bundler make gcc rsync
        bundle config path vendor/bundle
        bundle install --jobs=4

    - name: Build
      run: |
        bundle config path vendor/bundle
        scripts/build.sh

#    - name: Proofing
#      run: |
#        scripts/test.sh

    - name: Deploy
      if: ${{ github.event_name == 'push' && github.repository == 'polychromatic/website' && github.ref == 'refs/heads/master' }}
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      run: |
        mkdir -p $HOME/.ssh/
        chmod 700 $HOME/.ssh/
        echo -n "${{ secrets.SSH_CONFIG }}" > $HOME/.ssh/config
        echo -n "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_rsa
        echo -n "${{ secrets.SSH_KNOWN_HOSTS }}" > $HOME/.ssh/known_hosts
        chmod 600 $HOME/.ssh/id_rsa
        scripts/deploy.sh
