name: Test

on: [push, pull_request]

jobs:
  proofing:
    name: Proofing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Build
      run: JEKYLL_ENV=production bundle exec jekyll build

    - name: Check for problems
      run: scripts/test.sh
